name: Build Windows App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install absl-py altgraph arrow astunparse blinker certifi cffi charset-normalizer click colorama contourpy cors cryptography cycler dateparser et-xmlfile filelock Flask Flask-Cors Flask-JWT-Extended Flask-SQLAlchemy flatbuffers fonttools future gast gevent google-pasta greenlet grpcio h5py idna itsdangerous Jinja2 keras kiwisolver libclang macholib Markdown markdown-it-py MarkupSafe marshmallow matplotlib mdurl ml-dtypes moment namex numpy openpyxl opt_einsum optree packaging pandas pdf2image pillow protobuf pycparser pygame Pygments pyinstaller pyinstaller-hooks-contrib PyJWT PyOpenGL pyparsing PyQt5 PyQt5-Qt5 PyQt5-stubs PyQt5_sip PySocks pytesseract python-dateutil pytz regex requests requests-file rich setuptools six SQLAlchemy tensorboard tensorboard-data-server tensorflow termcolor times tkinterhtml tldextract tqdm types-python-dateutil typing_extensions tzdata tzlocal urllib3 Werkzeug wheel wrapt zope.event zope.interface
          
      - name: Generate EXE (with ALL dependencies)
        run: |
          pyinstaller --onefile --windowed `
            --hidden-import absl `
            --hidden-import altgraph `
            --hidden-import arrow `
            --hidden-import blinker `
            --hidden-import cffi `
            --hidden-import contourpy `
            --hidden-import cors `
            --hidden-import cryptography `
            --hidden-import cycler `
            --hidden-import dateparser `
            --hidden-import Flask `
            --hidden-import Flask_Cors `
            --hidden-import Flask_JWT_Extended `
            --hidden-import Flask_SQLAlchemy `
            --hidden-import fonttools `
            --hidden-import gast `
            --hidden-import gevent `
            --hidden-import google_pasta `
            --hidden-import grpcio `
            --hidden-import h5py `
            --hidden-import itsdangerous `
            --hidden-import keras `
            --hidden-import kiwisolver `
            --hidden-import macholib `
            --hidden-import markdown_it_py `
            --hidden-import marshmallow `
            --hidden-import mdurl `
            --hidden-import ml_dtypes `
            --hidden-import namex `
            --hidden-import openpyxl `
            --hidden-import opt_einsum `
            --hidden-import optree `
            --hidden-import pandas `
            --hidden-import pdf2image `
            --hidden-import protobuf `
            --hidden-import pygame `
            --hidden-import PyQt5 `
            --hidden-import pytesseract `
            --hidden-import regex `
            --hidden-import requests_file `
            --hidden-import rich `
            --hidden-import tensorboard `
            --hidden-import tensorflow `
            --hidden-import times `
            --hidden-import tkinterhtml `
            --hidden-import tldextract `
            --hidden-import tqdm `
            --hidden-import typing_extensions `
            --hidden-import tzlocal `
            --hidden-import Werkzeug `
            --hidden-import wrapt `
            --hidden-import zope.event `
            --hidden-import zope.interface `
            --collect-all absl `
            --collect-all altgraph `
            --collect-all arrow `
            --collect-all Flask `
            --collect-all keras `
            --collect-all matplotlib `
            --collect-all numpy `
            --collect-all pandas `
            --collect-all PyQt5 `
            --collect-all tensorflow `
            app.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: dist/app.exe
